scrape_configs:

  ## gather metrics of prometheus itself
- job_name: prometheus
  static_configs:
    - targets:
      - localhost:9090 # equivalent to "localhost:9090"

  ## gather the metrics of json_exporter application itself
# - job_name: json_exporter
#   static_configs:
#     - targets:
#       ## Location of the json exporter's real <hostname>:<port>
#       - localhost:7979 # equivalent to "localhost:7979"

- job_name: json
  metrics_path: /probe
  params:
    module: [if_stats]
  static_configs:
    - targets:
      - https://api.mist.com/api/v1/sites/:SITE/stats/switch_ports/search?mac=:MAC #One Target per switch
      - https://api.mist.com/api/v1/sites/:SITE/stats/switch_ports/search?mac=:MAC
      - https://api.mist.com/api/v1/sites/:SITE/stats/switch_ports/search?mac=:MAC
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      ## Location of the json exporter's real <hostname>:<port>
      replacement: localhost:7979 # equivalent to "localhost:7979"

  ## gather the metrics from third party json sources, via the json exporter